### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Jefersonnnn** [Jefersonnnn/JamesApp#2]
# TODO:

### Requisitos do Usuário

1. [x] **Registro de Usuário:**
    - [x] Os usuários devem poder se registrar na aplicação fornecendo um nome de usuário, email e senha.
    - [x] Encriptar senhas

2. [x] **Login de Usuário:**
    - [x] Os usuários devem poder fazer login na aplicação usando suas credenciais.

3. [ ] **Gerenciamento de Conta do Usuário:**
    - [ ] Os usuários devem poder atualizar suas informações de conta, como nome de usuário, email e senha.
    - [ ] Os usuários devem poder excluir suas contas, se desejarem.

### Gerenciamento de Clientes (Pessoas)

4. [x] **Registro de Clientes:**
    - [x] Os usuários devem poder adicionar informações de clientes, como nome e CPF.

5. [x] **Recuperação de Clientes:**
    - [x] Os usuários devem poder visualizar uma lista de todos os clientes (especificos do usuário) registrados na aplicação .

6. [x] **Atualização de Clientes:**
    - [x] Os usuários devem poder atualizar as informações dos clientes.

7. [x] **Exclusão de Clientes:**
    - [x] Os usuários devem poder excluir clientes quando necessário.

### Gerenciamento de Grupos

8. [ ] **Criação de Grupos:**
    - [ ] Os usuários devem poder criar grupos e atribuir nomes a eles, além de informações de pagamentos (data, valor).
    - [ ] Os usuários devem poder definir uma programação para execução automática dos pagamentos de grupo (JOB).

9. [x] **Recuperação de Grupos:**
    - [x] Os usuários devem poder ver uma lista de todos os grupos existentes (especificos do usuário).

10. [x] **Atualização de Grupos:**
    - [x] Os usuários devem poder atualizar informações sobre os grupos (especificos do usuário), como nome e programação de pagamento.

11. [x] **Exclusão de Grupos:**
    - [x] Os usuários devem poder excluir grupos quando necessário.

### Transações

Ainda pensar como uma transação irá vim de um webhook (de algum operador de pagamentos externo)

16. [x] **Registro de Transações:**
    - [x] Os usuários devem poder registrar transações, incluindo pagamentos e reembolsos, associados a faturas e clientes.

17. [x] **Recuperação de Transações:**
    - [x] Os usuários devem poder visualizar uma lista de todas as transações registradas.

18. [x] **Cálculo Automático do Saldo:**
    - [x] A aplicação deve calcular automaticamente o saldo de cada cliente com base nas transações registradas.

### Histórico de Participações

19. [ ] **Registro do Histórico de Participações:**
    - [ ] A aplicação deve manter um histórico das participações de clientes em grupos, incluindo datas de início e término de cada participação.

20. [ ] **Recuperação do Histórico de Participações:**
    - [ ] Os usuários devem poder visualizar o histórico de participações de um cliente em um grupo específico.

### JOB de Pagamento de Grupo

21. [ ] **Execução Automática do Pagamento de Grupo:**
    - [ ] A aplicação deve agendar um job que será executado periodicamente (por exemplo, mensalmente) para debitar o valor do grupo e atualizar o status dos clientes no grupo.

### Documentação da API

22. [ ] **Documentação de Rotas da API:**
    - [ ] A aplicação deve fornecer documentação clara das rotas da API, incluindo parâmetros, tipos de solicitação e exemplos de uso.

23. [ ] **Testes Automatizados:**
    - [ ] A aplicação deve incluir testes automatizados para garantir que todas as funcionalidades estejam funcionando corretamente.

**Comment by Jefersonnnn** [comment]
Retornos de Erros personalizados.
https://www.toptal.com/java/spring-boot-rest-api-error-handling

**Comment by Jefersonnnn** [comment]
Criar um sistema de auditoria, para saber quais as movimentações/alterações foram feitas.

Alterações de Usuários
Alteração de Transações

**Comment by Jefersonnnn** [comment]
Como trabalhar com paginação
https://www.baeldung.com/rest-api-pagination-in-spring
